[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.14.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.1"

[[constraint]]
  name = "sigs.k8s.io/controller-runtime"
  version = "v0.2.0-beta.1"

[[constraint]]
  name = "github.com/oracle/oci-go-sdk"
  version = "5.9.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "v1.10.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "v2.2.2"
