[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "9.0.0"
