[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.14.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.1"

[[constraint]]
  name = "sigs.k8s.io/controller-runtime"
  version = "v0.2.0-beta.1"
