apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simple-ingress
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /foo
        backend:
          serviceName: foo-svc
          servicePort: 80
      - path: /bar
        backend:
          serviceName: bar-svc
          servicePort: 80
